// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYMMwWPk8da_j4J_zIzMCYDIaTN4IgGUE',
    appId: '1:494148558291:web:a9ce123a05559dd9c0a326',
    messagingSenderId: '494148558291',
    projectId: 'base-flutter-25bd3',
    authDomain: 'base-flutter-25bd3.firebaseapp.com',
    storageBucket: 'base-flutter-25bd3.appspot.com',
    measurementId: 'G-XLVMDSTBNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5NbG37iq_bJhBlHzQKXLB7Gce0e_vEak',
    appId: '1:494148558291:android:9be1b4060db32e3bc0a326',
    messagingSenderId: '494148558291',
    projectId: 'base-flutter-25bd3',
    storageBucket: 'base-flutter-25bd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADbQ8CzjrmX8cenTDoxEJBSaiY9AT2T_Y',
    appId: '1:494148558291:ios:b40ad2a0c256ac25c0a326',
    messagingSenderId: '494148558291',
    projectId: 'base-flutter-25bd3',
    storageBucket: 'base-flutter-25bd3.appspot.com',
    iosBundleId: 'com.example.baseGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADbQ8CzjrmX8cenTDoxEJBSaiY9AT2T_Y',
    appId: '1:494148558291:ios:a6959662af96b885c0a326',
    messagingSenderId: '494148558291',
    projectId: 'base-flutter-25bd3',
    storageBucket: 'base-flutter-25bd3.appspot.com',
    iosBundleId: 'com.example.baseGetx.RunnerTests',
  );
}
